#!/bin/bash
#
# Generated by tools/generate-cli-targets.py. Do not edit by hand.
#
# Codex CLI's MCP-server registration and custom prompts are both
# confirmed global-only (see tools/generate-cli-targets.py's Codex
# section doc comment) - there is no project-relative equivalent Codex
# will discover on its own, unlike agents/*.toml (which IS project-
# scoped and needs no install step). This script performs the real
# global-install actions needed, using Codex's own official CLI where
# one exists rather than hand-editing ~/.codex/config.toml directly.
#
# Safe to re-run - removes any existing registration first.
#
set -euo pipefail

# Derived from this script's own location, never baked in at generation
# time. This file is checked into the repo, so a hardcoded absolute path
# here would publish the generating machine's home directory - and would
# be wrong for everyone who cloned anywhere else. See GATEWAY_COMMAND in
# tools/generate-cli-targets.py.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# The gateway is registered by NAME, resolved on PATH - the convention
# every MCP client documents. Install the launcher first so that name
# resolves.
LAUNCHER_DIR="${CLICKY_LOCAL_BIN:-$HOME/.local/bin}"
echo "--- Installing the clicky-gateway launcher into $LAUNCHER_DIR ---"
mkdir -p "$LAUNCHER_DIR"
ln -sf "$REPO_ROOT/skills/mcp-gateway/scripts/launch.sh" "$LAUNCHER_DIR/clicky-gateway"
case ":$PATH:" in
    *":$LAUNCHER_DIR:"*) ;;
    *) echo "    NOTE: $LAUNCHER_DIR is not on your PATH - add it to your shell profile:"
       echo '      export PATH="$HOME/.local/bin:$PATH"' ;;
esac

echo "--- Registering clicky-gateway MCP server globally (~/.codex/config.toml) ---"
codex mcp remove clicky-gateway >/dev/null 2>&1 || true
codex mcp add clicky-gateway -- clicky-gateway

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
echo "--- Installing custom prompts into $CODEX_HOME/prompts/ ---"
mkdir -p "$CODEX_HOME/prompts"
cp "$REPO_ROOT"/.codex/prompts/*.md "$CODEX_HOME/prompts/"

cat << 'EOF'

--- One more manual step: skills registration ---
Codex's skills.config is confirmed to only load from the global
~/.codex/config.toml (same project-relative limitation as MCP servers
and prompts above), but this script won't auto-edit that file's
unfamiliar [[skills.config]] section for you - add this block yourself
(or merge it if you already have other [[skills.config]] entries):

EOF
python3 - "$REPO_ROOT" << 'PYEOF'
import sys
from pathlib import Path
repo_root = sys.argv[1]
skills_dir = Path(repo_root) / "skills"
for skill_dir in sorted(skills_dir.iterdir()):
    skill_md = skill_dir / "SKILL.md"
    if skill_md.is_file():
        print(f'[[skills.config]]\npath = "{skill_md}"\nenabled = true\n')
PYEOF

cat << 'EOF'
--- Done. To dispatch Clicky agents, use: ---
  ./tools/run-clicky-agent.sh "your prompt here"
(not a bare `codex exec` call - see that script for why shell_tool must
be disabled for every Clicky session, and why the model is pinned.)
EOF
