#!/bin/bash
#
# coverage-ledger.sh - methodology coverage tracking keyed to OWASP WSTG /
# PTES identifiers.
#
# Why this exists: an engagement can run thousands of requests and still skip
# whole methodology phases. Without a ledger, "we found nothing" and "we never
# looked" are indistinguishable in the final report - which is the reporting
# equivalent of the timeout bug fixed in skills/mcp-gateway/server.py, and the
# reason PentestJudge (arXiv 2508.02921) judges an agent's TRAJECTORY against a
# rubric instead of only its end state.
#
# Statuses:
#   not_started    - default; nobody has done this
#   done           - actually performed (requires --evidence)
#   partial        - started but incomplete (requires --why)
#   skipped        - deliberately not done (requires --why)
#   not_applicable - cannot apply to this target (requires --why)
#
# `done` requires evidence and `skipped` requires a reason, so neither can be
# claimed by default. `gaps` is what report-agent must print.
#
# Usage:
#   coverage-ledger.sh init <session_dir>
#   coverage-ledger.sh mark <session_dir> <check_id> <status> [--evidence E] [--why W] [--agent A]
#   coverage-ledger.sh gaps <session_dir>        # everything not done/not_applicable
#   coverage-ledger.sh summary <session_dir>     # counts per phase
#   coverage-ledger.sh report <session_dir>      # markdown coverage table
#   coverage-ledger.sh catalog                   # list known check ids
set -uo pipefail

command -v jq >/dev/null 2>&1 || { echo "coverage-ledger.sh: jq is required" >&2; exit 2; }

LEDGER_REL="state/coverage.json"

# Catalog. Generated by tools/generate-coverage-catalog.py from the vendored
# OWASP WSTG checklist (skills/engagement-state/data/wstg-checklist.md), NOT
# typed by hand: an earlier revision hand-wrote these names from memory and got
# 25 of 36 wrong, including labelling WSTG-APIT-01 "Test GraphQL" when its
# official name is "API Reconnaissance". A report citing a WSTG ID against the
# wrong test name is worse than one citing no ID at all.
_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CATALOG_FILE="${CLICKY_COVERAGE_CATALOG:-$_HERE/../data/coverage-catalog.tsv}"

if [ ! -f "$CATALOG_FILE" ]; then
    echo "coverage-ledger.sh: catalog not found at $CATALOG_FILE" >&2
    echo "  Run: python3 tools/generate-coverage-catalog.py" >&2
    exit 2
fi

# id<TAB>phase<TAB>title, comments stripped.
CATALOG="$(grep -v '^#' "$CATALOG_FILE" | grep -v '^[[:space:]]*$')"

_ledger() { echo "$1/$LEDGER_REL"; }

_require() {
    local p; p="$(_ledger "$1")"
    [ -f "$p" ] || { echo "coverage-ledger.sh: no ledger at $p (run 'init')" >&2; exit 2; }
    echo "$p"
}

cmd_catalog() { printf '%s\n' "$CATALOG" | awk -F'\t' '{printf "%-16s %-10s %s\n", $1, $2, $3}'; }

cmd_init() {
    local session_dir="$1"
    mkdir -p "$session_dir/state"
    local p; p="$(_ledger "$session_dir")"
    if [ -f "$p" ]; then echo "$p"; return 0; fi
    printf '%s\n' "$CATALOG" | jq -R -s --arg now "$(date -Iseconds)" '
        {version: 1, created: $now, updated: $now,
         checks: (split("\n") | map(select(length > 0)) | map(split("\t") | {
            id: .[0], phase: .[1], title: .[2],
            status: "not_started", evidence: "", why: "", agent: "", updated: ""
         }))}' > "$p"
    echo "$p"
}

cmd_mark() {
    local session_dir="$1" id="$2" status="$3"; shift 3
    local p; p="$(_require "$session_dir")" || exit 2
    case "$status" in
        not_started|done|partial|skipped|not_applicable) ;;
        *) echo "coverage-ledger.sh: invalid status '$status'" >&2; exit 2 ;;
    esac
    local evidence="" why="" agent=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --evidence) evidence="$2"; shift 2 ;;
            --why) why="$2"; shift 2 ;;
            --agent) agent="$2"; shift 2 ;;
            *) shift ;;
        esac
    done
    if [ "$status" = "done" ] && [ -z "$evidence" ]; then
        echo "coverage-ledger.sh: '$id done' requires --evidence (the command or artifact that proves it ran)." >&2
        exit 3
    fi
    if { [ "$status" = "skipped" ] || [ "$status" = "not_applicable" ] || [ "$status" = "partial" ]; } && [ -z "$why" ]; then
        echo "coverage-ledger.sh: '$id $status' requires --why (a reader must know what was not covered and why)." >&2
        exit 3
    fi
    jq -e --arg id "$id" 'any(.checks[]; .id == $id)' "$p" >/dev/null || {
        echo "coverage-ledger.sh: unknown check id '$id' (see 'catalog')" >&2; exit 2; }
    local tmp; tmp="$(mktemp)"
    jq --arg id "$id" --arg st "$status" --arg ev "$evidence" --arg why "$why" \
       --arg agent "$agent" --arg now "$(date -Iseconds)" '
        .checks |= map(if .id == $id then
            .status = $st | .evidence = $ev | .why = $why | .agent = $agent | .updated = $now
        else . end) | .updated = $now' "$p" > "$tmp" && mv "$tmp" "$p"
    echo "$id -> $status"
}

cmd_gaps() {
    local p; p="$(_require "$1")" || exit 2
    jq -r '[.checks[] | select(.status != "done" and .status != "not_applicable")] as $g
           | if ($g | length) == 0 then "COVERAGE COMPLETE: every catalog check is done or not_applicable."
             else "COVERAGE GAPS (\($g | length) of \(.checks | length) checks):",
                  ($g[] | "  [\(.status)] \(.id)  \(.title)" + (if .why != "" then "  - \(.why)" else "" end))
             end' "$p"
}

cmd_summary() {
    local p; p="$(_require "$1")" || exit 2
    jq -c '{total: (.checks | length),
            by_status: ([.checks[].status] | group_by(.) | map({(.[0]): length}) | add // {}),
            gaps: ([.checks[] | select(.status != "done" and .status != "not_applicable")] | length)}' "$p"
}

cmd_report() {
    local p; p="$(_require "$1")" || exit 2
    echo "## Methodology Coverage (OWASP WSTG / PTES)"
    echo
    jq -r '"Checks: \(.checks | length) total, " +
           "\([.checks[] | select(.status=="done")] | length) done, " +
           "\([.checks[] | select(.status=="not_applicable")] | length) not applicable, " +
           "\([.checks[] | select(.status != "done" and .status != "not_applicable")] | length) NOT COVERED."' "$p"
    echo
    echo "| Check | Phase | Status | Evidence / Reason |"
    echo "|---|---|---|---|"
    jq -r '.checks[] | "| \(.id) | \(.phase) | \(.status) | \(if .evidence != "" then .evidence else .why end) |"' "$p"
}

case "${1:-}" in
    init)    shift; cmd_init "$@" ;;
    mark)    shift; cmd_mark "$@" ;;
    gaps)    shift; cmd_gaps "$@" ;;
    summary) shift; cmd_summary "$@" ;;
    report)  shift; cmd_report "$@" ;;
    catalog) shift; cmd_catalog "$@" ;;
    *) sed -n '/^# Usage:/,/^set -uo/p' "$0" | sed 's/^# \{0,1\}//;$d'; exit 1 ;;
esac
