#!/usr/bin/env python3
"""Generate the coverage-ledger catalog from the authoritative OWASP WSTG
checklist, plus the non-WSTG checks Clicky adds.

Why this exists: the catalog used to be a hand-written heredoc inside
coverage-ledger.sh. Every test name in it had been typed from memory, and an
audit against the real OWASP checklist found 25 of 36 names paraphrased and one
(WSTG-APIT-01) materially wrong - labelled "Test GraphQL" when the official
name is "API Reconnaissance". A report that cites a WSTG ID against the wrong
test name is worse than one citing no ID at all, so the names now come from the
vendored upstream file and are never typed by hand.

WSTG covers web applications. A network-service engagement also needs port and
service enumeration, source acquisition, and the PTES phases that precede
exploitation - those are added here under NET-*/SRC-*/PTES-* prefixes, clearly
distinguished from the WSTG-* IDs so nothing invented is ever mistaken for an
OWASP identifier.

Usage:
    python3 tools/generate-coverage-catalog.py            # write the catalog
    python3 tools/generate-coverage-catalog.py --check    # drift check only
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "skills" / "engagement-state" / "data"
CHECKLIST = DATA_DIR / "wstg-checklist.md"
CATALOG = DATA_DIR / "coverage-catalog.tsv"

# WSTG's 4-character category code -> the engagement phase Clicky groups it
# under. Names are WSTG's own section headings.
PHASE_BY_CATEGORY = {
    "INFO": "recon",
    "CONF": "config",
    "IDNT": "identity",
    "ATHN": "auth",
    "ATHZ": "authz",
    "SESS": "session",
    "INPV": "input",
    "ERRH": "errors",
    "CRYP": "crypto",
    "BUSL": "logic",
    "CLNT": "client",
    "APIT": "api",
}

# Checks WSTG does not cover, because WSTG scopes to web applications. These
# IDs are Clicky's own and deliberately do not use the WSTG- prefix.
LOCAL_CHECKS = [
    ("NET-01", "recon", "Full TCP port scan (all 65535 ports)"),
    ("NET-02", "recon", "UDP port scan (top ports minimum)"),
    ("NET-03", "recon", "Service version detection on every open port"),
    ("NET-04", "recon", "DNS and subdomain enumeration (domain targets)"),
    ("NET-05", "recon", "Host and OS fingerprinting"),
    ("SRC-01", "config", "Source acquisition (exposed .git/.svn, source maps, package manifests)"),
    ("SRC-02", "config", "Dependency vulnerability review of acquired manifests"),
    ("ART-01", "recon", "Read the application's own authoritative artifacts (route/build manifests, sitemaps, JS bundles) before wordlist enumeration"),
    ("PTES-TM-01", "modeling", "Threat model: enumerate and rank attack paths against the stated objective"),
    ("PTES-VA-01", "analysis", "Vulnerability analysis of discovered surface before exploitation"),
    ("PTES-PE-01", "postex", "Post-exploitation: pillage, pivot, and persistence assessment"),
]

ROW_RE = re.compile(r"^\|\s*(WSTG-([A-Z]{4})-\d{2})\s*\|\s*([^|]+?)\s*\|")


def build() -> list[tuple[str, str, str]]:
    if not CHECKLIST.is_file():
        sys.exit(f"generate-coverage-catalog: missing vendored checklist at {CHECKLIST}")
    rows: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for line in CHECKLIST.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        test_id, category, name = m.group(1), m.group(2), m.group(3)
        if test_id in seen:
            continue
        seen.add(test_id)
        phase = PHASE_BY_CATEGORY.get(category)
        if phase is None:
            sys.exit(
                f"generate-coverage-catalog: unknown WSTG category {category!r} in "
                f"{test_id} - upstream added a category; add it to PHASE_BY_CATEGORY."
            )
        rows.append((test_id, phase, name))
    if not rows:
        sys.exit("generate-coverage-catalog: parsed 0 WSTG rows - checklist format changed?")
    return LOCAL_CHECKS + rows


def render(rows) -> str:
    header = (
        "# Generated by tools/generate-coverage-catalog.py. Do not edit by hand.\n"
        "#\n"
        "# WSTG-* ids and names come verbatim from the vendored OWASP Web Security\n"
        "# Testing Guide checklist (skills/engagement-state/data/wstg-checklist.md,\n"
        "# CC BY-SA 4.0). NET-*/SRC-*/ART-*/PTES-* are Clicky's own additions for\n"
        "# network-service and methodology coverage WSTG does not address.\n"
        "#\n"
        "# id\tphase\ttitle\n"
    )
    return header + "".join(f"{i}\t{p}\t{t}\n" for i, p, t in rows)


def main() -> int:
    rows = build()
    out = render(rows)
    if "--check" in sys.argv:
        if not CATALOG.is_file():
            print(f"DRIFT: {CATALOG} does not exist"); return 1
        if CATALOG.read_text(encoding="utf-8") != out:
            print(f"DRIFT: {CATALOG} is out of date - re-run tools/generate-coverage-catalog.py")
            return 1
        print(f"coverage catalog is up to date ({len(rows)} checks).")
        return 0
    CATALOG.write_text(out, encoding="utf-8")
    wstg = sum(1 for r in rows if r[0].startswith("WSTG-"))
    print(f"Wrote {CATALOG.relative_to(REPO_ROOT)}: {len(rows)} checks "
          f"({wstg} from OWASP WSTG, {len(rows) - wstg} Clicky-local).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
