#!/bin/bash
#
# Generated by tools/generate-cli-targets.py. Do not edit by hand.
#
# Copilot CLI has no `/pentest`-equivalent custom command (confirmed: no
# custom slash-command system exists in this version) and no separate
# "primary agent" concept - the orchestrator agent itself is the entry
# point. This wraps `copilot --agent pentest-orchestrator` with the flag
# non-interactive mode requires (confirmed: "--allow-all-tools ... required
# for non-interactive mode").
#
# No install step needed first (unlike Codex) - every generated agent's
# MCP server registration is embedded in its own frontmatter, which is
# confirmed to work standalone (see tools/generate-cli-targets.py's
# Copilot section doc comment for why workspace-level registration is
# deliberately NOT used here).
#
set -euo pipefail
exec copilot --agent pentest-orchestrator --allow-all-tools "$@"
