#!/bin/bash
#
# Generated by tools/generate-cli-targets.py. Do not edit by hand.
#
# Wraps `codex exec` with the two flags every Clicky Codex session needs
# - confirmed live, not defaults, see tools/generate-cli-targets.py's
# Codex section doc comment for the full evidence trail:
#
#   -m gpt-5.4         the one model confirmed to reliably expose MCP
#                    tools in exec sessions (Codex's own default model
#                    hits an open upstream bug, openai/codex#32101)
#   --disable shell_tool
#                    removes the built-in shell tool - Codex has no
#                    `permission: deny`-style mechanism, this is the
#                    confirmed-working lever, and it's scoped to just
#                    this invocation (not a persistent global config
#                    change) so the operator's other Codex usage is
#                    unaffected
#
# Run .codex/install.sh once first (registers the gateway + prompts
# globally - Codex confirmed to never discover either from a
# project-relative path).
#
set -euo pipefail
exec codex exec -m gpt-5.4 --disable shell_tool "$@"
